### ISSUE TITLE
Cant join?

### ISSUE THREAD

**Issue by 1Emin** [EternalsDev/Growtopia-Proxy#2]
I already added hosts file things. 

After putted GTPS ip to server.h but how we know server port (i putted 17250 but still didnt work)?

**Comment by ferlitopym** [comment]
> I already added hosts file things.
> 
> After putted GTPS ip to server.h but how we know server port (i putted 17250 but still didnt work)?

You need server_data.php reader tools to know port of gtps @1Emin

**Comment by 1Emin** [comment]
> 

Can you help me about this? I want to update this proxy as a good one.

**Comment by ferlitopym** [comment]
> > 
> 
> Can you help me about this? I want to update this proxy as a good one.

Sure just dm me IWasHuman#3218 or contactme on instagram : @levihs_store
@1Emin

**Comment by e-lyte** [comment]
> I already added hosts file things.
> 
> After putted GTPS ip to server.h but how we know server port (i putted 17250 but still didnt work)?

Hello @1Emin, for this most servers use port 17091, and some use other ports as well. To find out what port is used on the target server, you can easily use a server data reader for gtps

**Comment by 1Emin** [comment]
Thanks for helping me about this. Worked. <3

**Comment by DiazKun** [comment]
hello, how to build it, I tried to build using bash but got an error.

**Comment by e-lyte** [comment]
You can build using Visual Studio, check README.md for more information

**Comment by verdeckt** [comment]
hey @EternalsDev can you check here?

**Comment by verdeckt** [comment]
![image](https://user-images.githubusercontent.com/47688719/162003653-dadfce8f-f814-4eee-8b0a-c4ae295558df.png)
